// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqXW4MjDY5pOnIv9BQz9b5LRHJ82jITVQ',
    appId: '1:75765673184:web:0345052f444ebc9248f485',
    messagingSenderId: '75765673184',
    projectId: 'smart-lock-application-66a02',
    authDomain: 'smart-lock-application-66a02.firebaseapp.com',
    storageBucket: 'smart-lock-application-66a02.firebasestorage.app',
    measurementId: 'G-YBYJWP05ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv_vbhK9oT24H9qg0HVCS74APqE_CNi-c',
    appId: '1:75765673184:android:daf0bc662550578048f485',
    messagingSenderId: '75765673184',
    projectId: 'smart-lock-application-66a02',
    storageBucket: 'smart-lock-application-66a02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgu-liYtOk2XzxIZELSLBFgl8xYyqQhVg',
    appId: '1:75765673184:ios:8ec988fefd4d661448f485',
    messagingSenderId: '75765673184',
    projectId: 'smart-lock-application-66a02',
    storageBucket: 'smart-lock-application-66a02.firebasestorage.app',
    iosBundleId: 'com.example.smartLock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgu-liYtOk2XzxIZELSLBFgl8xYyqQhVg',
    appId: '1:75765673184:ios:8ec988fefd4d661448f485',
    messagingSenderId: '75765673184',
    projectId: 'smart-lock-application-66a02',
    storageBucket: 'smart-lock-application-66a02.firebasestorage.app',
    iosBundleId: 'com.example.smartLock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqXW4MjDY5pOnIv9BQz9b5LRHJ82jITVQ',
    appId: '1:75765673184:web:024580cb14018dfe48f485',
    messagingSenderId: '75765673184',
    projectId: 'smart-lock-application-66a02',
    authDomain: 'smart-lock-application-66a02.firebaseapp.com',
    storageBucket: 'smart-lock-application-66a02.firebasestorage.app',
    measurementId: 'G-1V068WWF2H',
  );
}
